name: dart_meteor
description: This library make connection between meteor backend and flutter app easily. Design to work seamlessly with StreamBuilder and FutureBuilder.
version: 2.0.0
homepage: https://github.com/tanutapi/dart_meteor

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  rxdart: ^0.24.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
