name: dart_meteor
description: This library make connection between meteor backend and flutter app easily. Design to work seamlessly with StreamBuilder and FutureBuilder.
version: 2.1.4
homepage: https://github.com/tanutapi/dart_meteor

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  rxdart: ^0.27.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  collection: ^1.15.0