name: dart_meteor
description: This library make connection between meteor backend and flutter app easily. Design to work seamlessly with StreamBuilder and FutureBuilder.
version: 1.0.8
homepage: https://github.com/tanutapi/dart_meteor
author: Tanut Apiwong <tanutapi@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  rxdart: ^0.24.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
